import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { marginBottom: 20 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 5 },
  subtitle: { fontSize: 14, color: '#666', marginBottom: 20 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 10, borderBottom: 1, paddingBottom: 5 },
  scoreBox: { padding: 15, backgroundColor: '#f0f4f8', borderRadius: 5, marginBottom: 20 },
  scoreText: { fontSize: 32, fontWeight: 'bold', color: '#2563eb' },
  categoryText: { fontSize: 14, fontWeight: 'bold', marginTop: 5 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 5 },
  tableCol: { flex: 1, fontSize: 10 },
  correct: { color: '#10b981' },
  incorrect: { color: '#ef4444' }
})

export function PDFReport({ attempt }: { attempt: any }) {
  const percentage = Math.round((attempt.total_score / attempt.max_score) * 100)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Quiz Performance Report</Text>
          <Text style={styles.subtitle}>{attempt.quizzes.title}</Text>
        </View>

        <View style={styles.scoreBox}>
          <Text style={styles.scoreText}>{percentage}%</Text>
          <Text style={styles.categoryText}>Level: {attempt.category}</Text>
          <Text style={{ fontSize: 12, marginTop: 10 }}>
            Scored {attempt.total_score} out of {attempt.max_score} points
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Answer Breakdown</Text>
          <View style={styles.tableRow}>
            <Text style={[styles.tableCol, { flex: 0.1 }]}>#</Text>
            <Text style={[styles.tableCol, { flex: 0.6 }]}>Question</Text>
            <Text style={[styles.tableCol, { flex: 0.3 }]}>Result</Text>
          </View>
          {attempt.attempt_answers.map((answer: any, index: number) => (
            <View key={answer.id} style={styles.tableRow}>
              <Text style={[styles.tableCol, { flex: 0.1 }]}>{index + 1}</Text>
              <Text style={[styles.tableCol, { flex: 0.6 }]}>{answer.questions.question_text}</Text>
              <Text style={[
                styles.tableCol, 
                { flex: 0.3 }, 
                answer.is_correct ? styles.correct : styles.incorrect
              ]}>
                {answer.is_correct ? 'Correct' : 'Incorrect'}
              </Text>
            </View>
          ))}
        </View>

        <Text style={{ fontSize: 10, color: '#999', marginTop: 40, textAlign: 'center' }}>
          Generated by otaQku Quiz App on {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  )
}
